/*
SPDX-FileCopyrightText: 2026 Humdek, University of Bern
SPDX-License-Identifier: MPL-2.0
*/
/**
 * Style registry — the runtime catalog of every CMS style the SelfHelp
 * ecosystem can render.
 *
 * It has two halves:
 *
 *   `BASE_STYLE_REGISTRY` — closed, compile-time-constant catalog of core
 *      styles shipped by this package. Used to derive the `TStyleName`
 *      union and to give renderers compile-time coverage of every core
 *      style.
 *
 *   `PLUGIN_STYLE_REGISTRY` — runtime-mutable map populated by plugin
 *      packages through `extendStyleRegistry()` at boot. Plugin entries
 *      are tagged with their `pluginId` so the renderer can show
 *      "Open on web" fallbacks for backend-declared styles that the
 *      current build does not bundle.
 *
 * Adding a *core* style:
 *   1. Add the per-style interface in `src/types/styles/<group>.ts`.
 *   2. Extend `TStyle` in `src/types/styles/unknown.ts`.
 *   3. Add the entry to `BASE_STYLE_REGISTRY` below.
 *   4. Both apps will fail to compile until they add an impl.
 *
 * Adding a *plugin* style:
 *   The plugin's `definePlugin()` call goes through
 *   `@selfhelp/shared/plugin-sdk`, which routes the entries to
 *   `extendStyleRegistry()` internally. Do not edit this file for plugin
 *   styles.
 */

import type { TStyleName } from '../types/styles/unknown';

/**
 * Concrete render targets a CMS style can support. The web frontend
 * renders `web`; the mobile app renders `mobile`.
 */
export type TConcretePlatform = 'web' | 'mobile';

/**
 * Where a style may be placed in the section tree:
 *   - `any`          (default) — page root or inside any container.
 *   - `rootOnly`     — page/root level only (e.g. a page-overlay style).
 *   - `containerOnly`— only inside a parent container, never at page root.
 *
 * Distinct from parent/child `rel_styles_allowed_relationships`: placement is a
 * coarse root-vs-container rule the CMS picker enforces in addition to the
 * fine-grained compound parent/child rules.
 */
export type TStylePlacement = 'any' | 'rootOnly' | 'containerOnly';

/**
 * CMS-facing render target of a style. Mirrors the backend
 * `styles.id_render_target` (`styleRenderTargets` lookup) and the
 * `renderTarget` field returned by the style schema/catalog API. `both`
 * expands to `['web','mobile']`. A platform's dispatcher silently skips a
 * style whose render target excludes it — distinct from the
 * "compatible-but-unimplemented" `UnknownStyle` / "Open on web" fallback.
 *
 * Page render target is NOT modelled here: a page's web/mobile/both scope is
 * the existing `pageAccessTypes` value, never a duplicate page platform field.
 */
export type TStylePlatform = TConcretePlatform | 'both';

export interface IStyleRegistryEntry {
    /** Human description for docs / tooling. */
    description: string;
    /** UX category for grouping in tools / cookbook. */
    category:
        | 'auth'
        | 'layout'
        | 'typography'
        | 'media'
        | 'interactive'
        | 'forms'
        | 'composite'
        | 'plugin';
    /**
     * Whether the style can have child sections (mirrors backend
     * `styles.can_have_children`). Renderers use this to short-circuit
     * children traversal.
     */
    canHaveChildren: boolean;
    /**
     * Render targets this style supports (compile-time fallback for the
     * backend `renderTarget`). Omitted = both platforms (`['web','mobile']`),
     * which is the default for every established core style. A mobile-only
     * style sets `['mobile']`; a web-only style sets `['web']`. The renderer
     * reads this through `getStylePlatforms()` / `isStyleSupportedOnPlatform()`
     * and silently skips styles that do not target the current platform.
     *
     * Runtime filtering should prefer the per-section `renderTarget` from the
     * backend payload when present (installed catalog data may differ from the
     * app build); this registry value is the compile-time source of truth.
     */
    platforms?: readonly TConcretePlatform[];
    /**
     * Placement rule in the section tree. Omitted = `any`. The CMS add-section
     * picker hides `rootOnly` styles when adding as a child and `containerOnly`
     * styles when adding at page root.
     */
    placement?: TStylePlacement;
}

/**
 * Plugin-contributed registry entry. Same shape as the base entry plus
 * the owning `pluginId`, used by renderers to decide on fallbacks.
 */
export interface IPluginStyleRegistryEntry extends IStyleRegistryEntry {
    /** Plugin that registered this style (e.g. `sh2-shp-survey-js`). */
    pluginId: string;
    /** Source plugin package version, useful for diagnostics. */
    pluginVersion?: string;
}

/**
 * Compile-time core registry. Keys here drive `TStyleName` (declared in
 * `types/styles/unknown.ts`); both files must stay in sync.
 */
export const BASE_STYLE_REGISTRY = {
    // ===== auth =====
    login: { description: 'User login form', category: 'auth', canHaveChildren: false },
    register: { description: 'User registration form', category: 'auth', canHaveChildren: false },
    validate: { description: 'Email/account validation flow', category: 'auth', canHaveChildren: true },
    'reset-password': { description: 'Reset password form', category: 'auth', canHaveChildren: false },
    'two-factor-auth': { description: 'Two-factor auth code form', category: 'auth', canHaveChildren: false },
    profile: { description: 'User profile management', category: 'auth', canHaveChildren: false },

    // ===== layout =====
    container: { description: 'Mantine Container with responsive max-width', category: 'layout', canHaveChildren: true },
    box: { description: 'Generic Mantine Box wrapper', category: 'layout', canHaveChildren: true },
    flex: { description: 'Mantine Flex layout', category: 'layout', canHaveChildren: true },
    group: { description: 'Mantine Group horizontal layout', category: 'layout', canHaveChildren: true },
    stack: { description: 'Mantine Stack vertical layout', category: 'layout', canHaveChildren: true },
    'simple-grid': { description: 'Mantine SimpleGrid', category: 'layout', canHaveChildren: true },
    grid: { description: 'Mantine Grid', category: 'layout', canHaveChildren: true },
    'grid-column': { description: 'Mantine Grid.Col', category: 'layout', canHaveChildren: true },
    space: { description: 'Mantine Space spacer', category: 'layout', canHaveChildren: false },
    divider: { description: 'Mantine Divider', category: 'layout', canHaveChildren: false },
    paper: { description: 'Mantine Paper surface', category: 'layout', canHaveChildren: true },
    center: { description: 'Mantine Center alignment', category: 'layout', canHaveChildren: true },
    'scroll-area': { description: 'Mantine ScrollArea', category: 'layout', canHaveChildren: true },
    card: { description: 'Mantine Card', category: 'layout', canHaveChildren: true },
    'card-segment': { description: 'Mantine Card.Section', category: 'layout', canHaveChildren: true },
    'aspect-ratio': { description: 'Mantine AspectRatio wrapper', category: 'layout', canHaveChildren: true },
    'background-image': { description: 'Mantine BackgroundImage', category: 'layout', canHaveChildren: true },

    // ===== typography =====
    title: { description: 'Mantine Title', category: 'typography', canHaveChildren: false },
    text: { description: 'Mantine Text', category: 'typography', canHaveChildren: false },
    code: { description: 'Mantine Code (inline / block)', category: 'typography', canHaveChildren: false },
    highlight: { description: 'Mantine Highlight', category: 'typography', canHaveChildren: false },
    blockquote: { description: 'Mantine Blockquote', category: 'typography', canHaveChildren: false },
    'html-tag': { description: 'Generic HTML tag wrapper (web), maps to View on RN', category: 'typography', canHaveChildren: true },
    kbd: { description: 'Mantine Kbd', category: 'typography', canHaveChildren: false },
    typography: { description: 'Mantine Typography wrapper', category: 'typography', canHaveChildren: true },
    fieldset: { description: 'Mantine Fieldset', category: 'typography', canHaveChildren: true },
    spoiler: { description: 'Mantine Spoiler reveal', category: 'typography', canHaveChildren: true },

    // ===== media =====
    image: { description: 'Mantine Image / RN Image', category: 'media', canHaveChildren: false },
    video: { description: 'HTML5 video / expo-video', category: 'media', canHaveChildren: false },
    audio: { description: 'HTML5 audio / expo-audio', category: 'media', canHaveChildren: false },
    figure: { description: 'Figure with caption', category: 'media', canHaveChildren: true },
    carousel: { description: 'Embla on web, reanimated-carousel on RN', category: 'media', canHaveChildren: true },

    // ===== interactive =====
    button: { description: 'Mantine Button / HeroUI Button', category: 'interactive', canHaveChildren: false },
    link: { description: 'Anchor / Pressable navigation', category: 'interactive', canHaveChildren: false },
    'action-icon': { description: 'Mantine ActionIcon', category: 'interactive', canHaveChildren: false },
    alert: { description: 'Mantine Alert', category: 'interactive', canHaveChildren: true },
    badge: { description: 'Mantine Badge', category: 'interactive', canHaveChildren: false },
    avatar: { description: 'Mantine Avatar', category: 'interactive', canHaveChildren: false },
    chip: { description: 'Mantine Chip', category: 'interactive', canHaveChildren: false },
    indicator: { description: 'Mantine Indicator dot', category: 'interactive', canHaveChildren: true },
    'theme-icon': { description: 'Mantine ThemeIcon', category: 'interactive', canHaveChildren: false },
    notification: { description: 'Mantine Notification', category: 'interactive', canHaveChildren: false },

    // ===== forms =====
    'form-log': { description: 'Append-only form (one row per submit)', category: 'forms', canHaveChildren: true },
    'form-record': { description: 'Per-user record form', category: 'forms', canHaveChildren: true },
    input: { description: 'Plain HTML input', category: 'forms', canHaveChildren: false },
    'text-input': { description: 'Mantine TextInput', category: 'forms', canHaveChildren: false },
    textarea: { description: 'Mantine Textarea', category: 'forms', canHaveChildren: false },
    'rich-text-editor': { description: 'Tiptap editor on web; native inline-format toolbar editor on mobile', category: 'forms', canHaveChildren: false },
    select: { description: 'HTML select / Mantine Select', category: 'forms', canHaveChildren: false },
    radio: { description: 'Mantine Radio / RadioGroup', category: 'forms', canHaveChildren: false },
    checkbox: { description: 'Mantine Checkbox', category: 'forms', canHaveChildren: false },
    slider: { description: 'Mantine Slider', category: 'forms', canHaveChildren: false },
    'range-slider': { description: 'Mantine RangeSlider', category: 'forms', canHaveChildren: false },
    datepicker: { description: 'Mantine DatePicker', category: 'forms', canHaveChildren: false },
    switch: { description: 'Mantine Switch', category: 'forms', canHaveChildren: false },
    combobox: { description: 'Mantine Combobox', category: 'forms', canHaveChildren: false },
    'color-input': { description: 'Mantine ColorInput', category: 'forms', canHaveChildren: false },
    'color-picker': { description: 'Mantine ColorPicker', category: 'forms', canHaveChildren: false },
    'file-input': { description: 'Mantine FileInput / DocumentPicker on RN', category: 'forms', canHaveChildren: false },
    'number-input': { description: 'Mantine NumberInput', category: 'forms', canHaveChildren: false },
    'segmented-control': { description: 'Mantine SegmentedControl', category: 'forms', canHaveChildren: false },
    rating: { description: 'Mantine Rating', category: 'forms', canHaveChildren: false },
    progress: { description: 'Mantine Progress', category: 'forms', canHaveChildren: false },
    'progress-root': { description: 'Mantine Progress.Root', category: 'forms', canHaveChildren: true },
    'progress-section': { description: 'Mantine Progress.Section', category: 'forms', canHaveChildren: false },

    // ===== composite =====
    accordion: { description: 'Mantine Accordion', category: 'composite', canHaveChildren: true },
    'accordion-item': { description: 'Mantine Accordion.Item', category: 'composite', canHaveChildren: true },
    tabs: { description: 'Mantine Tabs', category: 'composite', canHaveChildren: true },
    tab: { description: 'Mantine Tabs.Tab + Tabs.Panel pair', category: 'composite', canHaveChildren: true },
    timeline: { description: 'Mantine Timeline', category: 'composite', canHaveChildren: true },
    list: { description: 'Mantine List', category: 'composite', canHaveChildren: true },
    'list-item': { description: 'Mantine List.Item', category: 'composite', canHaveChildren: true },
    'entry-list': { description: 'Data-driven list of entries (form-log table)', category: 'composite', canHaveChildren: true },
    'entry-record': { description: 'Single-record container', category: 'composite', canHaveChildren: true },
    'entry-record-delete': { description: 'Inline delete confirmation for an entry', category: 'composite', canHaveChildren: false },
    loop: { description: 'Loop / repeater over backend-provided rows', category: 'composite', canHaveChildren: true },
    'timeline-item': { description: 'A single entry inside a timeline (child-only)', category: 'composite', canHaveChildren: true },

    // ===== system / data / reference (established backend catalog) =====
    'no-access': { description: 'Access-denied surface shown when the user lacks page access', category: 'auth', canHaveChildren: false },
    missing: { description: 'Generic "content missing" system surface', category: 'auth', canHaveChildren: false },
    'not-found': { description: 'Page-not-found system surface', category: 'auth', canHaveChildren: false },
    version: { description: 'Build/version diagnostic surface', category: 'auth', canHaveChildren: false },
    'ref-container': { description: 'Renders content referenced from another section', category: 'layout', canHaveChildren: true },
    'data-container': { description: 'Data-scoped container (renders subtree against a data scope)', category: 'layout', canHaveChildren: true },
    'show-user-input': { description: 'Displays previously submitted user input as a list/card view', category: 'forms', canHaveChildren: false },
} as const satisfies Record<string, IStyleRegistryEntry>;

/**
 * Backward-compatible alias for the core registry. Pre-plugin code
 * imported `STYLE_REGISTRY`; that import still works and still resolves
 * to the closed core map. Plugin-aware code should call
 * `getMergedStyleRegistry()` to see plugin entries too.
 */
export const STYLE_REGISTRY = BASE_STYLE_REGISTRY;

export type TStyleRegistryKey = keyof typeof BASE_STYLE_REGISTRY;

/**
 * Compile-time guard: every key in the core registry must be a valid
 * core TStyleName, and every core TStyleName must be a core registry
 * key. Plugin styles intentionally bypass this check (they live in
 * `PLUGIN_STYLE_REGISTRY`).
 */
export type _AssertRegistryMatchesStyleName = TStyleName extends TStyleRegistryKey
    ? TStyleRegistryKey extends TStyleName
        ? true
        : never
    : never;

// ===== plugin registry =====

const PLUGIN_STYLE_REGISTRY: Record<string, IPluginStyleRegistryEntry> = {};

/** Plugins that have already registered, used to detect double registration. */
const REGISTERED_PLUGIN_KEYS = new Map<string, Set<string>>();

/**
 * Register additional CMS styles contributed by a plugin. Called from
 * `definePlugin()` inside `@selfhelp/shared/plugin-sdk`; plugins should
 * not call this directly.
 *
 * Rules:
 *   - Plugin style names must not collide with `BASE_STYLE_REGISTRY`.
 *   - Plugin style names must not collide with any other plugin's
 *     already-registered styles.
 *   - Returns a disposer that removes the entries (used by uninstall
 *     and tests).
 */
export function extendStyleRegistry(
    entries: Record<string, IStyleRegistryEntry>,
    options: { pluginId: string; pluginVersion?: string },
): () => void {
    const { pluginId, pluginVersion } = options;
    const ownedKeys = REGISTERED_PLUGIN_KEYS.get(pluginId) ?? new Set<string>();
    const addedKeys: string[] = [];

    for (const [name, entry] of Object.entries(entries)) {
        if (Object.prototype.hasOwnProperty.call(BASE_STYLE_REGISTRY, name)) {
            throw new Error(
                `[shared/registry] plugin '${pluginId}' tried to register core style '${name}'.`,
            );
        }
        const existing = PLUGIN_STYLE_REGISTRY[name];
        if (existing && existing.pluginId !== pluginId) {
            throw new Error(
                `[shared/registry] plugin '${pluginId}' tried to register style '${name}' already owned by '${existing.pluginId}'.`,
            );
        }
        PLUGIN_STYLE_REGISTRY[name] = {
            ...entry,
            pluginId,
            pluginVersion,
        };
        ownedKeys.add(name);
        addedKeys.push(name);
    }

    REGISTERED_PLUGIN_KEYS.set(pluginId, ownedKeys);

    return function dispose() {
        for (const key of addedKeys) {
            const existing = PLUGIN_STYLE_REGISTRY[key];
            if (existing && existing.pluginId === pluginId) {
                delete PLUGIN_STYLE_REGISTRY[key];
                ownedKeys.delete(key);
            }
        }
        if (ownedKeys.size === 0) {
            REGISTERED_PLUGIN_KEYS.delete(pluginId);
        }
    };
}

/**
 * Live merged registry: core entries plus plugin-contributed entries.
 * Plugin entries override nothing — collisions throw in
 * `extendStyleRegistry` — so this map is safe to consume directly.
 */
export function getMergedStyleRegistry(): Record<string, IStyleRegistryEntry | IPluginStyleRegistryEntry> {
    return {
        ...BASE_STYLE_REGISTRY,
        ...PLUGIN_STYLE_REGISTRY,
    };
}

/**
 * Return only the plugin half of the registry. Useful for the renderer
 * to decide which styles need a fallback ("Open on web" on mobile) and
 * which `pluginId` they belong to.
 */
export function getPluginStyleRegistry(): Record<string, IPluginStyleRegistryEntry> {
    return { ...PLUGIN_STYLE_REGISTRY };
}

/**
 * Test-only helper: wipe every plugin contribution. Not exported from
 * the package root; available through the plugin SDK testing module.
 *
 * @internal
 */
export function _resetPluginStyleRegistry(): void {
    for (const key of Object.keys(PLUGIN_STYLE_REGISTRY)) {
        delete PLUGIN_STYLE_REGISTRY[key];
    }
    REGISTERED_PLUGIN_KEYS.clear();
}
