/*
SPDX-FileCopyrightText: 2026 Humdek, University of Bern
SPDX-License-Identifier: MPL-2.0
*/
/**
 * TypeScript mirror of `selfhelp.plugins.lock.json`. This file lives at
 * the project root of the backend deployment and is the deterministic
 * source of truth for which plugin versions are installed, what migrations
 * ran, which checksums are pinned, and what mobile packages each EAS
 * profile bundles.
 *
 * The lock file is written atomically by the install/update command. It
 * is NEVER edited by hand.
 */

export interface IPluginLockMigration {
    /** Doctrine migration class name. */
    className: string;
    /** Migration file SHA-256 hash, recorded for tamper detection. */
    sha256: string;
    /** ISO datetime the migration was executed. */
    executedAt: string;
    /** Whether `down()` is declared safe by the plugin. */
    safeDown: boolean;
}

export interface IPluginLockMobileEntry {
    /** EAS profile name (e.g. `production-default`, `production-bern`). */
    profile: string;
    /** npm package + version that this profile bundles for the plugin. */
    package: string;
    version: string;
}

export interface IPluginLockEntry {
    /** Plugin id. */
    id: string;
    /** Pinned plugin version (the manifest version that was installed). */
    version: string;
    /** SDK contract version the plugin targets. */
    pluginApiVersion: string;
    /** Trust level recorded at install time. */
    trustLevel: 'official' | 'reviewed' | 'untrusted';
    /** Capabilities granted at install time. */
    capabilities: string[];
    /** Source descriptor that produced the install. */
    source: {
        kind: 'public-registry' | 'private-registry' | 'git' | 'local';
        url?: string;
        gitSha?: string;
        registryUrl?: string;
    };
    /** Backend Composer package + version, if any. */
    backend?: {
        package: string;
        version: string;
        bundleClass: string;
    };
    /** Frontend npm package + version, if any. */
    frontend?: {
        package: string;
        version: string;
    };
    /** Per-EAS-profile mobile package pin. */
    mobile?: IPluginLockMobileEntry[];
    /** SHA-256 checksum of the published artifact. */
    checksumSha256: string;
    /** Optional Ed25519 signature, base64. */
    signatureEd25519?: string;
    /** Hashes of every migration this plugin has executed. */
    migrations: IPluginLockMigration[];
    /** Plugin-owned style names contributed at install time. */
    ownedStyles: string[];
    /** Plugin-owned API route names contributed at install time. */
    ownedApiRoutes: string[];
    /** Plugin-owned realtime topics contributed at install time. */
    ownedRealtimeTopics: string[];
    /** Plugin-owned lookup type codes (`plugin_owned`) contributed at install time. */
    ownedLookupTypeCodes: string[];
    /** Feature flags shipped with the plugin and their default state. */
    featureFlags: { key: string; defaultEnabled: boolean }[];
    /** Whether the plugin is currently enabled. */
    enabled: boolean;
    /** ISO datetime of the install/update event. */
    installedAt: string;
    /** ISO datetime of the last update. */
    updatedAt: string;
    /** Optional notes that the installer wants to surface. */
    notes?: string;
}

/**
 * Root document of `selfhelp.plugins.lock.json`.
 */
export interface IPluginLock {
    /** Schema version. */
    schemaVersion: '1.0';
    /** Generated by tag, includes the CMS version that wrote the file. */
    generatedBy: string;
    /** ISO datetime the lock file was last written. */
    generatedAt: string;
    /** Install mode that produced this lock file. */
    installMode: 'development' | 'managed' | 'trusted';
    /** Installed plugins. */
    plugins: IPluginLockEntry[];
}
